name: Learn GitHub Actions

on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  learn:
    runs-on: ubuntu-latest

    steps:
      - name: Get the source code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Check the folder name
        run: ls -la

      - name: Check Node and NPM version
        run: |
          node -v
          npm -v

      # -------------------------
      # Backend
      # -------------------------

      - name: Install backend dependencies
        working-directory: ./userManagmentBackend
        run: npm ci

      - name: Generate Prisma Client
        working-directory: ./userManagmentBackend
        env:
          DATABASE_URL: postgresql://postgres:postgres@db:5432/dummy
        run: npx prisma generate

      - name: Build the backend
        working-directory: ./userManagmentBackend
        run: npm run build

      # -------------------------
      # Frontend
      # -------------------------

      - name: Install frontend dependencies
        working-directory: ./userManagementFrontend
        run: npm ci

      - name: Build the frontend
        working-directory: ./userManagementFrontend
        run: npm run build

      # -------------------------
      # Login to GitHub Container Registry
      # -------------------------

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # -------------------------
      # Get lowercase GitHub username
      # -------------------------

      - name: Set lowercase GitHub username
        run: echo "IMAGE_OWNER=${GITHUB_ACTOR,,}" >> "$GITHUB_ENV"

      # -------------------------
      # Backend Docker image
      # -------------------------

      - name: Build and push backend Docker image
        run: |
          docker build \
            -t ghcr.io/${{ env.IMAGE_OWNER }}/user-management-backend:latest \
            ./userManagmentBackend

          docker push \
            ghcr.io/${{ env.IMAGE_OWNER }}/user-management-backend:latest

      # -------------------------
      # Frontend Docker image
      # -------------------------

      - name: Build and push frontend Docker image
        run: |
          docker build \
            -t ghcr.io/${{ env.IMAGE_OWNER }}/user-management-frontend:latest \
            ./userManagementFrontend

          docker push \
            ghcr.io/${{ env.IMAGE_OWNER }}/user-management-frontend:latest