name: Learn GitHub Actions

on:
  push:

jobs:
  learn:
    runs-on: ubuntu-latest

    steps:

      - name: Who am I?
        run: whoami

      - name: Where am I?
        run: pwd

      - name: What OS am I using?
        run: uname -a

      - name: What files are here?
        run: ls -la

      - name: What Git version?
        run: git --version