name: Learn GitHub Actions

on:
  push:

jobs:
  learn:
    runs-on: ubuntu-latest

    steps:

      - name: get the source code
        uses: actions/checkout@v4

      - name: set up node
        uses: action/setup-node@v4
        with:
          node-version: 22

      - name : check node version
        run: node -v

      - name : check npm version
        run: npm -v 